name: ht_app_settings_api
description: An API client implementation for managing user application settings via an HTTP backend, part of the Headlines Toolkit (HT) ecosystem.
repository: https://github.com/headlines-toolkit/ht-app-settings-api
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies: 
  ht_app_settings_client:
    git:
      url: https://github.com/headlines-toolkit/ht-app-settings-client.git
  ht_http_client:
    git:
      url: https://github.com/headlines-toolkit/ht-http-client.git
  ht_shared:
    git:
      url: https://github.com/headlines-toolkit/ht-shared.git
      
dev_dependencies:
  mocktail: ^1.0.4
  test: ^1.25.8
  very_good_analysis: ^7.0.0
